In [1]:
import numpy as np

In [2]:
# リストの作成
my_list1 = [1,2,3,4]

In [3]:
# numpy形式に変換
my_array1 = np.array(my_list1)

In [6]:
my_array1

array([1, 2, 3, 4])

In [7]:
# 多次元配列を作成する
my_list2 = [11,22,33,44]
my_lists = [my_list1, my_list2]

In [8]:
# 多次元配列が作成された
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
# numpy型の多次元配列の作成
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2, 4)

In [12]:
# 0を５個持った配列を作成する
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros(5).dtype

dtype('float64')

In [15]:
# 各成分が1の5行５列の行列を作成
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
# 単位行列の作成
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])