In [1]:
import numpy as np

In [2]:
arr = np.arange(9).reshape((3, 3))

In [3]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# 行を列と入れ替える
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
# 行と列を入れ替える
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
# 行と列を入れ替える
arr.transpose(0,1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 行と列を入れ替える
arr.transpose(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])